name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

      - name: Build & Test
        working-directory: src
        run: |
          dotnet restore
          dotnet build --no-restore
          dotnet test --no-build --verbosity normal

      - name: Build Fable App
        working-directory: src/Parser.WebUI
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          path: src/Parser.WebUI/dist
