name: ci_solution

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  job_ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

      - name: Build & Test
        working-directory: src
        run: |
          dotnet restore
          dotnet build --no-restore
          dotnet test --no-build --verbosity normal
