name: ci_webui

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  job_ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

      - name: Build Fable App
        working-directory: src/Parser.WebUI
        run: |
          dotnet tool restore
          npm install
          npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          path: src/Parser.WebUI/dist
